Starter code for this assignment was provided by Professor Gordon and appears throughout the homework.

First, the Git envinornment is configured.

In [1]:
!pip install tensorflowjs

    100% |████████████████████████████████| 13.9MB 3.1MB/s 
    100% |████████████████████████████████| 307kB 24.7MB/s 
keras 2.2.2 has requirement keras-applications==1.0.4, but you'll have keras-applications 1.0.6 which is incompatible.
keras 2.2.2 has requirement keras-preprocessing==1.0.2, but you'll have keras-preprocessing 1.0.5 which is incompatible.
  Found existing installation: numpy 1.14.6
    Uninstalling numpy-1.14.6:
      Successfully uninstalled numpy-1.14.6
  Found existing installation: Keras 2.2.4
    Uninstalling Keras-2.2.4:
      Successfully uninstalled Keras-2.2.4


In [0]:
# your github username
USER_NAME = "mspitz6" 

# the email associated with your commits
# (may not matter if you leave it as this)
USER_EMAIL = "mrs2299@columbia.edu" 

# the user token you've created (see the lecture 8 slides for instructions)
TOKEN = "" 

# site name
# for example, if my user_name is "foo", then this notebook will create
# a site at https://foo.github.io/hw4/
SITE_NAME = "hw4"

In [0]:
!git config --global user.email {USER_NAME}
!git config --global user.name  {USER_EMAIL}

In [4]:
import os
repo_path = USER_NAME + '.github.io'
if not os.path.exists(os.path.join(os.getcwd(), repo_path)):
  !git clone https://{USER_NAME}:{TOKEN}@github.com/{USER_NAME}/{USER_NAME}.github.io

Cloning into 'mspitz6.github.io'...
remote: Enumerating objects: 166, done.
remote: Counting objects: 100% (166/166), done.
remote: Compressing objects: 100% (125/125), done.
remote: Total 166 (delta 49), reused 156 (delta 39), pack-reused 0
Receiving objects: 100% (166/166), 7.27 MiB | 10.54 MiB/s, done.
Resolving deltas: 100% (49/49), done.


In [5]:
os.chdir(repo_path)
!git pull

Already up to date.


In [0]:
project_path = os.path.join(os.getcwd(), SITE_NAME)
if not os.path.exists(project_path): 
  os.mkdir(project_path)
os.chdir(project_path)

In [0]:
# DO NOT MODIFY
MODEL_DIR = os.path.join(project_path, "model_js")
if not os.path.exists(MODEL_DIR):
  os.mkdir(MODEL_DIR)

As an example, we will create and vectorize a few toy documents provided by Professor's starter code.

In [0]:
# A few snippets from Alice in Wonderland
ex1 = "Alice was beginning to get very tired of sitting by her sister on the bank."
ex2 = "Once or twice she had peeped into the book her sister was reading, but it had no pictures or conversations in it."

# Dracula
ex3 = "Buda-Pesth seems a wonderful place."
ex4 = "Left Munich at 8:35 P. M., on 1st May, arriving at Vienna early next morning."

# Illiad
ex5 = "Scepticism was as much the result of knowledge, as knowledge is of scepticism."
ex6 = "To be content with what we at present know, is, for the most part, to shut our ears against conviction."

In [0]:
x_train_example = [ex1, ex2, ex3, ex4, ex5, ex6]
y_train_example = [0, 0, 1, 1, 2, 2] # Indicating which book each sentence is from

Additionally, for this asignment we will also analyze the first 1,000 words from three different books found on Gutenberg.org to serve as training data for a text classifier.



In [10]:
import nltk
nltk.download('all')

[nltk_data] Downloading collection 'all'
[nltk_data]    | 
[nltk_data]    | Downloading package abc to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/abc.zip.
[nltk_data]    | Downloading package alpino to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/alpino.zip.
[nltk_data]    | Downloading package biocreative_ppi to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/biocreative_ppi.zip.
[nltk_data]    | Downloading package brown to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/brown.zip.
[nltk_data]    | Downloading package brown_tei to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/brown_tei.zip.
[nltk_data]    | Downloading package cess_cat to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/cess_cat.zip.
[nltk_data]    | Downloading package cess_esp to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/cess_esp.zip.
[nltk_data]    | Downloading package chat80 to /root/nltk_data...
[nltk_data]    |   Unzipp

True

In [0]:
b1 = nltk.corpus.gutenberg.sents('carroll-alice.txt')[3:]
b2 = nltk.corpus.gutenberg.sents('shakespeare-hamlet.txt')[3:]
b3 = nltk.corpus.gutenberg.sents('melville-moby_dick.txt')[3:]

In [12]:
print('sentences in carroll-alice.txt: ' + str(len(b1)))
print('sentences in shakespeare-hamlet.txt: ' + str(len(b2)))
print('sentences in melville-moby_dick.txt: ' + str(len(b3)))

sentences in carroll-alice.txt: 1700
sentences in shakespeare-hamlet.txt: 3103
sentences in melville-moby_dick.txt: 10056


In [0]:
books = [b1[:1000], b2[:1000], b3[:1000]]

x_train = []
for book in books:
  for sent in book:
    
    clean_sent = []
    for word in sent:
      
      if word.isalpha():
        clean_sent.append(word)

    clean_sent = " ".join(clean_sent)
    x_train.append(clean_sent)

In [0]:
y_train = [[0 for i in range(1000)], [1 for i in range(1000)], [2 for i in range(1000)]]
y_train = [label for book_label in y_train for label in book_label]

In [15]:
print(len(x_train)); print(len(y_train))

3000
3000


Next, the documents are tokenized. This was done for both the toy example data as well as the 3,000 sentences taken from the books on Gutenberg.org.

In [16]:
max_len = 20
num_words = 3000
from keras.preprocessing.text import Tokenizer

Using TensorFlow backend.


In [0]:
# Fit the tokenizer on the training data
t_ex = Tokenizer(num_words=num_words, filters='!"#$%&()*+,-./:;<=>?@[\]^_`{|}~”—')
t_ex.fit_on_texts(x_train_example)

In [0]:
# Fit the tokenizer on the training data
t = Tokenizer(num_words=num_words, filters='!"#$%&()*+,-./:;<=>?@[\]^_`{|}~”—')
t.fit_on_texts(x_train)

In [19]:
print(t.word_index)

{'the': 1, 'and': 2, 'a': 3, 'to': 4, 'of': 5, 'i': 6, 'it': 7, 'in': 8, 'that': 9, 'you': 10, 'was': 11, 'she': 12, 'as': 13, 'but': 14, 'his': 15, 'with': 16, 'my': 17, 'is': 18, 'this': 19, 'for': 20, 'he': 21, 'not': 22, 's': 23, 'at': 24, 'said': 25, 'all': 26, 'be': 27, 'on': 28, 'alice': 29, 'me': 30, 'so': 31, 'what': 32, 'had': 33, 'there': 34, 'her': 35, 't': 36, 'by': 37, 'or': 38, 'one': 39, 'they': 40, 'no': 41, 'out': 42, 'then': 43, 'him': 44, 'from': 45, 'like': 46, 'little': 47, 'very': 48, 'if': 49, 'your': 50, 'up': 51, 'now': 52, 'do': 53, 'which': 54, 'were': 55, 'into': 56, 'when': 57, 'are': 58, 'about': 59, 'we': 60, 'would': 61, 'have': 62, 'time': 63, 'down': 64, 'more': 65, 'd': 66, 'an': 67, 'lord': 68, 'ham': 69, 'whale': 70, 'some': 71, 'know': 72, 'see': 73, 'how': 74, 'could': 75, 'them': 76, 'did': 77, 'will': 78, 'well': 79, 'here': 80, 'who': 81, 'good': 82, 'thought': 83, 'our': 84, 'again': 85, 'such': 86, 'much': 87, 'their': 88, 'say': 89, 'most':

In [0]:
metadata = {
  'word_index': t.word_index,
  'max_len': max_len,
  'vocabulary_size': num_words,
}

After fitting the tokenizer on the training data, I implemented three models; the first one is for the toy example data. Whereas, Model 1 & Model 2 will fit the Gutenberg.org text data. Model 1 simply has an embedding layer, while Model 2 is a deep RNN with LSTM layers.

In [0]:
embedding_size = 32
n_classes = 3
epochs = 10 #12

import keras

In [0]:
model = keras.Sequential()
model.add(keras.layers.Embedding(num_words, embedding_size, input_shape=(max_len,)))
model.add(keras.layers.Flatten())
model.add(keras.layers.Dense(3, activation='softmax'))
model.compile('adam', 'sparse_categorical_crossentropy', metrics=['accuracy'])

In [23]:
model1 = keras.Sequential()
model1.add(keras.layers.Embedding(num_words, embedding_size, input_shape=(max_len,)))
model1.add(keras.layers.Flatten())
model1.add(keras.layers.Dense(3, activation='softmax'))
model1.compile('adam', 'sparse_categorical_crossentropy', metrics=['accuracy'])
model1.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_2 (Embedding)      (None, 20, 32)            96000     
_________________________________________________________________
flatten_2 (Flatten)          (None, 640)               0         
_________________________________________________________________
dense_2 (Dense)              (None, 3)                 1923      
Total params: 97,923
Trainable params: 97,923
Non-trainable params: 0
_________________________________________________________________


In [24]:
model2 = keras.Sequential()
model2.add(keras.layers.Embedding(num_words, embedding_size, input_shape=(max_len,)))
model2.add(keras.layers.LSTM(64, return_sequences=True))
model2.add(keras.layers.LSTM(64))
model2.add(keras.layers.Dense(3, activation='softmax'))
model2.compile('adam', 'sparse_categorical_crossentropy', metrics=['accuracy'])
model2.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_3 (Embedding)      (None, 20, 32)            96000     
_________________________________________________________________
lstm_1 (LSTM)                (None, 20, 64)            24832     
_________________________________________________________________
lstm_2 (LSTM)                (None, 64)                33024     
_________________________________________________________________
dense_3 (Dense)              (None, 3)                 195       
Total params: 154,051
Trainable params: 154,051
Non-trainable params: 0
_________________________________________________________________


The text data is then vectorized for both the toy example and the 3,000 sentences in order to fit the data to the corresponding models. Following this process, I tested the accurcy of all the models.

In [0]:
from keras.preprocessing.sequence import pad_sequences

x_train_example = t_ex.texts_to_sequences(x_train_example)
x_train_example = pad_sequences(x_train_example, maxlen=max_len, padding='post')

In [26]:
model.fit(x_train_example, y_train_example, epochs=epochs)

Epoch 1/10
6/6 [==============================] - 2s 349ms/step - loss: 1.0873 - acc: 0.5000
Epoch 2/10
6/6 [==============================] - 0s 2ms/step - loss: 1.0696 - acc: 0.8333
Epoch 3/10
6/6 [==============================] - 0s 956us/step - loss: 1.0493 - acc: 1.0000
Epoch 4/10
6/6 [==============================] - 0s 923us/step - loss: 1.0280 - acc: 1.0000
Epoch 5/10
6/6 [==============================] - 0s 1ms/step - loss: 1.0063 - acc: 1.0000
Epoch 6/10
6/6 [==============================] - 0s 1ms/step - loss: 0.9843 - acc: 1.0000
Epoch 7/10
6/6 [==============================] - 0s 980us/step - loss: 0.9623 - acc: 1.0000
Epoch 8/10
6/6 [==============================] - 0s 1ms/step - loss: 0.9402 - acc: 1.0000
Epoch 9/10
6/6 [==============================] - 0s 916us/step - loss: 0.9181 - acc: 1.0000
Epoch 10/10
6/6 [==============================] - 0s 966us/step - loss: 0.8961 - acc: 1.0000


In [27]:
test_example = "Left Munich at 8:35 P. M., on 1st May, arriving at Vienna early next morning."

sample_test = t_ex.texts_to_sequences([test_example])
sample_test = pad_sequences(sample_test, maxlen=max_len, padding='post')

preds = model.predict(sample_test)
print(preds)
import numpy as np
print(np.argmax(preds))

[[0.28254116 0.44405916 0.2733997 ]]
1


As you can see above, the base embedding model accurately classified the toy example test text.

In [28]:
x_train = t.texts_to_sequences(x_train)
x_train = pad_sequences(x_train, maxlen=max_len, padding='pre')
x_train = x_train.astype('float32')
print(x_train)

[[  41. 1057.   38. ... 1057.   38.  607.]
 [ 890.    5.  281. ...  498.   37.   35.]
 [  77.   29.  119. ...  305.   92.  260.]
 ...
 [   0.    0.    0. ...  547.   45.    9.]
 [   0.    0.    6. ...  102.  859.   52.]
 [   7.   55.    3. ...  753.   77.  546.]]


In [29]:
x_train.shape

(3000, 20)

In [30]:
model1.fit(x_train, y_train, epochs=epochs)

Epoch 1/10
3000/3000 [==============================] - 1s 189us/step - loss: 1.0396 - acc: 0.4723
Epoch 2/10
3000/3000 [==============================] - 0s 133us/step - loss: 0.8447 - acc: 0.6910
Epoch 3/10
3000/3000 [==============================] - 0s 135us/step - loss: 0.5843 - acc: 0.8250
Epoch 4/10
3000/3000 [==============================] - 0s 133us/step - loss: 0.3908 - acc: 0.8937
Epoch 5/10
3000/3000 [==============================] - 0s 129us/step - loss: 0.2807 - acc: 0.9290
Epoch 6/10
3000/3000 [==============================] - 0s 132us/step - loss: 0.2159 - acc: 0.9487
Epoch 7/10
3000/3000 [==============================] - 0s 128us/step - loss: 0.1713 - acc: 0.9620
Epoch 8/10
3000/3000 [==============================] - 0s 133us/step - loss: 0.1399 - acc: 0.9657
Epoch 9/10
3000/3000 [==============================] - 0s 132us/step - loss: 0.1193 - acc: 0.9690
Epoch 10/10
3000/3000 [==============================] - 0s 131us/step - loss: 0.1038 - acc: 0.9727


In [31]:
model2.fit(x_train, y_train, epochs=epochs)

Epoch 1/10
3000/3000 [==============================] - 11s 4ms/step - loss: 0.9645 - acc: 0.5403
Epoch 2/10
3000/3000 [==============================] - 10s 3ms/step - loss: 0.4981 - acc: 0.8047
Epoch 3/10
3000/3000 [==============================] - 10s 3ms/step - loss: 0.2722 - acc: 0.8920
Epoch 4/10
3000/3000 [==============================] - 10s 3ms/step - loss: 0.1768 - acc: 0.9240
Epoch 5/10
3000/3000 [==============================] - 10s 3ms/step - loss: 0.1478 - acc: 0.9407
Epoch 6/10
3000/3000 [==============================] - 10s 3ms/step - loss: 0.1074 - acc: 0.9623
Epoch 7/10
3000/3000 [==============================] - 10s 3ms/step - loss: 0.0866 - acc: 0.9627
Epoch 8/10
3000/3000 [==============================] - 10s 3ms/step - loss: 0.0720 - acc: 0.9710
Epoch 9/10
3000/3000 [==============================] - 10s 3ms/step - loss: 0.0618 - acc: 0.9763
Epoch 10/10
3000/3000 [==============================] - 10s 3ms/step - loss: 0.0693 - acc: 0.9747


In [0]:
books = [b1[1000:1500], b2[1000:1500], b3[1000:1500]]

x_test = []
for book in books:
  for sent in book:
    
    clean_sent = []
    for word in sent:
      
      if word.isalpha():
        clean_sent.append(word)

    clean_sent = " ".join(clean_sent)
    x_test.append(clean_sent)

In [0]:
y_test = [[0 for i in range(500)], [1 for i in range(500)], [2 for i in range(500)]]
y_test = [label for book_label in y_test for label in book_label]

In [34]:
print(x_test[55])
print(y_test[55])

Alice thought she had never seen such a curious croquet ground in her life it was all ridges and furrows the balls were live hedgehogs the mallets live flamingoes and the soldiers had to double themselves up and to stand on their hands and feet to make the arches
0


When evaluating accuracy on an independent test set the base model with soley an embedding layer, Model 1, slightly underperforms the deep RNN with LSTMs, Model 2.

In [0]:
x_test = t.texts_to_sequences(x_test)
x_test = pad_sequences(x_test, maxlen=max_len, padding='pre')
x_test = x_test.astype('float32')

In [36]:
test_loss, test_acc = model1.evaluate(x_test, y_test)
print(test_acc)

1500/1500 [==============================] - 0s 136us/step
0.7653333331743876


In [37]:
test_loss, test_acc = model2.evaluate(x_test, y_test)
print(test_acc)

1500/1500 [==============================] - 2s 1ms/step
0.7746666661898295


Finally, I converted & loaded the optimal model, Model 2, into the browser.

In [38]:
import json
import tensorflowjs as tfjs

metadata_json_path = os.path.join(MODEL_DIR, 'metadata.json')
json.dump(metadata, open(metadata_json_path, 'wt'))
tfjs.converters.save_keras_model(model2, MODEL_DIR)
print('\nSaved model artifcats in directory: %s' % MODEL_DIR)


Saved model artifcats in directory: /content/mspitz6.github.io/hw4/model_js


In [0]:
index_html = """
<!doctype html>

<body>
  <style>
    #textfield {
      font-size: 120%;
      width: 60%;
      height: 200px;
    }
  </style>
  <h1>
    Gutenberg Text Classifier
  </h1>
  <hr>
  <div class="create-model">
    <button id="load-model" style="display:none">Load model</button>
  </div>
  <div>
    <div>
      <span>Vocabulary size: </span>
      <span id="vocabularySize"></span>
    </div>
    <div>
      <span>Max length: </span>
      <span id="maxLen"></span>
    </div>
  </div>
  <hr>
  <div>
    <select id="example-select" class="form-control">
      <option value="example1">Alice in Wonderland</option>
      <option value="example2">Hamlet</option>
      <option value="example3">Moby Dick</option>
    </select>
  </div>
  <div>
    <textarea id="text-entry"></textarea>
  </div>
  <hr>
  <div>
    <span id="status">Standing by.</span>
  </div>

  <script src='https://cdn.jsdelivr.net/npm/@tensorflow/tfjs/dist/tf.min.js'></script>
  <script src='index.js'></script>
</body>
"""

In [0]:
index_js = """
const HOSTED_URLS = {
  model:
      'model_js/model.json',
  metadata:
      'model_js/metadata.json'
};

const examples = {
  'example1':
      'Alice thought she had never seen such a curious croquet ground in her life it was all ridges and furrows the balls were live hedgehogs the mallets live flamingoes and the soldiers had to double themselves up and to stand on their hands and feet to make the arches',
  'example2':
      'To be or not to be that is the Question Whether tis Nobler in the minde to suffer The Slings and Arrowes of outragious Fortune Or to take Armes against a Sea of troubles And by opposing end them',
  'example3':
      'Some gamesome wights will tell you that they have to plant weeds there they dont grow naturally that they import Canada thistles that they have to send beyond seas for a spile to stop a leak in an oil cask that pieces of wood in Nantucket are carried about like bits of the true cross in Rome that people there plant toadstools before their houses'
};

function status(statusText) {
  console.log(statusText);
  document.getElementById('status').textContent = statusText;
}

function showMetadata(metadataJSON) {
  document.getElementById('vocabularySize').textContent =
      metadataJSON['vocabulary_size'];
  document.getElementById('maxLen').textContent =
      metadataJSON['max_len'];
}

function settextField(text, predict) {
  const textField = document.getElementById('text-entry');
  textField.value = text;
  doPredict(predict);
}

function setPredictFunction(predict) {
  const textField = document.getElementById('text-entry');
  textField.addEventListener('input', () => doPredict(predict));
}

function disableLoadModelButtons() {
  document.getElementById('load-model').style.display = 'none';
}

function doPredict(predict) {
  const textField = document.getElementById('text-entry');
  const result = predict(textField.value);
  score_string = "Class scores: ";
  for (var x in result.score) {
    score_string += x + " ->  " + result.score[x].toFixed(3) + ", "
  }
  //console.log(score_string);
  status(
      score_string + ' elapsed: ' + result.elapsed.toFixed(3) + ' ms)');
}

function prepUI(predict) {
  setPredictFunction(predict);
  const testExampleSelect = document.getElementById('example-select');
  testExampleSelect.addEventListener('change', () => {
    settextField(examples[testExampleSelect.value], predict);
  });
  settextField(examples['example1'], predict);
}

async function urlExists(url) {
  status('Testing url ' + url);
  try {
    const response = await fetch(url, {method: 'HEAD'});
    return response.ok;
  } catch (err) {
    return false;
  }
}

async function loadHostedPretrainedModel(url) {
  status('Loading pretrained model from ' + url);
  try {
    const model = await tf.loadModel(url);
    status('Done loading pretrained model.');
    disableLoadModelButtons();
    return model;
  } catch (err) {
    console.error(err);
    status('Loading pretrained model failed.');
  }
}

async function loadHostedMetadata(url) {
  status('Loading metadata from ' + url);
  try {
    const metadataJson = await fetch(url);
    const metadata = await metadataJson.json();
    status('Done loading metadata.');
    return metadata;
  } catch (err) {
    console.error(err);
    status('Loading metadata failed.');
  }
}

class Classifier {

  async init(urls) {
    this.urls = urls;
    this.model = await loadHostedPretrainedModel(urls.model);
    await this.loadMetadata();
    return this;
  }

  async loadMetadata() {
    const metadata =
        await loadHostedMetadata(this.urls.metadata);
    showMetadata(metadata);
    this.maxLen = metadata['max_len'];
    console.log('maxLen = ' + this.maxLen);
    this.wordIndex = metadata['word_index']
  }

  predict(text) {
    // Convert to lower case and remove all punctuations.
    const inputText =
        text.trim().toLowerCase().replace(/(\.|\,|\!)/g, '').split(' ');
    // Look up word indices.
    const inputBuffer = tf.buffer([1, this.maxLen], 'float32');
    for (let i = 0; i < inputText.length; ++i) {
      const word = inputText[i];
      inputBuffer.set(this.wordIndex[word], 0, i);
      //console.log(word, this.wordIndex[word], inputBuffer);
    }
    const input = inputBuffer.toTensor();
    //console.log(input);

    status('Running inference');
    const beginMs = performance.now();
    const predictOut = this.model.predict(input);
    //console.log(predictOut.dataSync());
    const score = predictOut.dataSync();//[0];
    predictOut.dispose();
    const endMs = performance.now();

    return {score: score, elapsed: (endMs - beginMs)};
  }
};

async function setup() {
  if (await urlExists(HOSTED_URLS.model)) {
    status('Model available: ' + HOSTED_URLS.model);
    const button = document.getElementById('load-model');
    button.addEventListener('click', async () => {
      const predictor = await new Classifier().init(HOSTED_URLS);
      prepUI(x => predictor.predict(x));
    });
    button.style.display = 'inline-block';
  }

  status('Standing by.');
}

setup();
"""

In [0]:
with open('index.html','w') as f:
  f.write(index_html)
  
with open('index.js','w') as f:
  f.write(index_js)

In [42]:
!ls

index.html  index.js  model_js


In [43]:
!git add . 
!git commit -m "colab -> github"
!git push https://{USER_NAME}:{TOKEN}@github.com/{USER_NAME}/{USER_NAME}.github.io/ master

[master c722a51] colab -> github
 1 file changed, 0 insertions(+), 0 deletions(-)
 rewrite hw4/model_js/group1-shard1of1 (91%)
Counting objects: 5, done.
Delta compression using up to 2 threads.
Compressing objects: 100% (5/5), done.
Writing objects: 100% (5/5), 558.42 KiB | 10.15 MiB/s, done.
Total 5 (delta 1), reused 0 (delta 0)
remote: Resolving deltas: 100% (1/1), completed with 1 local object.
To https://github.com/mspitz6/mspitz6.github.io/
   a4f8659..c722a51  master -> master


In [44]:
print("Now, visit https://%s.github.io/%s/" % (USER_NAME, SITE_NAME))

Now, visit https://mspitz6.github.io/hw4/
